### ISSUE TITLE
Crashes on Android 5.1.1 on Nexus 5

### ISSUE THREAD

**Issue by ryanniehaus** [jlmalone/Android-Google-Voice-Locations#4]
The app crashes on startup (service is enabled), and anytime I try to open the app.
Started after I updated to 5.1.1

**Comment by jlmalone** [comment]
Thanks, do you have a stacktrace?

**Comment by ryanniehaus** [comment]
Nope.  I don't, but I can probably do that.  Is that in the developer menu, or do I have to have the SDK installed for that?  I did report the error using the OS crash GUI, but I'm not sure if that gives you a stacktrace as well.

**Comment by ryanniehaus** [comment]
I'm new to Android development, so it'll take me a bit to figure that out.

**Comment by jlmalone** [comment]
It may be related to android recently breaking client login API

**Comment by ryanniehaus** [comment]
OK.  I'll do my best to help.  I've always wanted to get involved with an open source project, and your app seems like a good place to start.  Kudos on the work you've done so far.  I've depended on your app a lot since I found it a few years ago.  I've done some Java programming, but it's been years.  I mostly work on C/C++ apps for *nix based systems (some Windows as well).

**Comment by jlmalone** [comment]
Great to finally have someone interested in participating. :-)

**Comment by goodevilgenius** [comment]
Same for me on a Nexus 6. This app was working fine until a few days ago when I got the update for 5.1.1. On 5.1.0, it was working fine.

**Comment by goodevilgenius** [comment]
It just started working for me again. Was this the result of a change Google made?

**Comment by ryanniehaus** [comment]
Working for me too.  I'm guessing it was an update by Google that fixed it.  I haven't noticed an update for this app itself.

**Comment by jlmalone** [comment]
Yes, we had some chatter in the Google Voice Java API that it was working
again on all API tests
